repos:
  - repo: https://github.com/b4pm-devops/sostrades-pre-commit.git
    rev: v1.1.2
    hooks:
    - id: update-headers
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      - id: ruff
        args: [
          --fix,
          --exit-non-zero-on-fix,
          --config=ruff.toml,
        ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: LICENSES/headers
      - id: check-yaml
        # !reference is specific to gitlab
        # !! prefix is specific to mkdocs
        exclude: \.gitlab-ci.yml|mkdocs.yml
      - id: check-added-large-files
      - id: check-json
      - id: pretty-format-json
        args: [
          --autofix,
          --no-sort-keys,
        ]
        exclude: \.ipynb
      - id: check-toml
      - id: destroyed-symlinks
      - id: check-symlinks
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.44.0
    hooks:
    - id: markdownlint
      args: [
        --fix,
        --disable,
        MD024,
        ]
