
@startuml
class         SOSCoupling
SoSDisciplineBuilder <|- SOSCoupling
MDAChain <|- SOSCoupling
SoSDiscipline <|- SoSDisciplineBuilder

MDODiscipline <|- SoSDiscipline

SoSDisciplineBuilder <|- SoSDisciplineScatter
@enduml