@startuml
User -> ExecEngine: configure
ExecEngine -> DataManager: load_values(data)
ExecEngine -> Factory: configure
Factory -> Builder: configure
Builder -> DisciplineProxy: configure
DisciplineProxy -> Configuration: configure
Configuration -> MultiScenarioBuilder: init
MultiScenarioBuilder -> Builder: configure
Builder -> MDOCouplingStructure: compute_reduced_graph
Builder -> DisciplineProxy: configure

User -> ExecEngine: prepare_exec
Builder -> DisciplineProxy: prepare_exec
DisciplineProxy -> MDODisciplineWrapp : prepare_exec
ExecEngine -> MDAChain : init

User -> ExecEngine: execute(data)
ExecEngine -> DataManager: load_values(data)
ExecEngine -> MDAChain: execute
MDAChain -> MDODiscipline : execute
@enduml
