
@startuml
class Configuration
class SoSDisciplineBuilder{
status
}

class Discipline{
status
execute()
}

class SOSDiscipline{
status
DESC_IN
DESC_OUT
run()
}

class ExecutionEngine{
disciplines
configure()
build()
execute()
}

class         DisciplineProxy{
status
input_data_names
output_data_names
}

class         SOSFactory{
disciplines_proxys
}

class MDOCouplingStructure
class DisciplineWrapp


DisciplineProxy *-- Configuration
DisciplineProxy *-- DisciplineWrapp
DisciplineProxy --* SoSDisciplineBuilder

DisciplineWrapp "1" *-- "0..*" SOSDiscipline
DisciplineWrapp "1" *-- "1" Discipline

Configuration -> MDOCouplingStructure

ExecutionEngine -> DisciplineProxy
@enduml
