@startuml
User -> ExecEngine: configure
ExecEngine -> Factory: build

Factory -> SoSDisciplineScatter: build
SoSDisciplineScatter -> Builder: build
Builder -> Discipline: __init__

User -> DataManager: set_values_from_dict
User -> ExecEngine : execute
ExecEngine -> SOSCoupling: execute
SOSCoupling -> Discipline: execute
@enduml
