
@startuml
class         SOSCoupling
SoSDisciplineBuilder <|- SOSCoupling
MDAChain <|- SOSCoupling
SoSDiscipline <|- SoSDisciplineBuilder

Discipline <|- SoSDiscipline

SoSDisciplineBuilder <|- SoSDisciplineScatter
@enduml
