
@startuml
class Configuration
class SoSDisciplineBuilder{
status
}

class MDODiscipline{
status
execute()
}

class SOSDiscipline{
status
DESC_IN
DESC_OUT
run()
}

class ExecutionEngine{
mdo_disciplines
configure()
build()
execute()
}

class         DisciplineProxy{
status
input_data_names
output_data_names
}

class         SOSFactory{
disciplines_proxys
}

class MDOCouplingStructure
class MDODisciplineWrapp


DisciplineProxy *-- Configuration
DisciplineProxy *-- MDODisciplineWrapp
DisciplineProxy --* SoSDisciplineBuilder

MDODisciplineWrapp "1" *-- "0..*" SOSDiscipline
MDODisciplineWrapp "1" *-- "1" MDODiscipline

Configuration -> MDOCouplingStructure

ExecutionEngine -> DisciplineProxy
@enduml